# Site settings
title: dosrc
email: wdkrgst@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This land is a exhibition for article.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dosrc.com" # the base hostname & protocol for your site
#twitter_username: vandykai
github_username:  vandykai

# Build settings
markdown: kramdown
